---
# Configures PHP to work with MySQL

- name: install mysql drivers
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present  # won't update if done under an hour ago
  with_items:
    - php5-mysql
